[features]
seeds = false
skip-lint = false
[programs.devnet]
anchor_template = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./key.json"

[scripts]
test = "yarn run scripts/index.ts"
